!MNH_LIC COPYRIGHT 1994-2014 CNRS, METEO-FRANCE AND UNIVERSITE PAUL SABATIER
!MNH_LIC THIS IS PART OF THE MESO-NH SOFTWARE GOVERNED BY THE CECILL-C LICENCE
!MNH_LIC VERSION 1. SEE LICENSE, CECILL-C_V1-EN.TXT AND CECILL-C_V1-FR.TXT
!MNH_LIC FOR DETAILS. VERSION 1.
!-----------------------------------------------------------------
!--------------- SPECIAL SET OF CHARACTERS FOR RCS INFORMATION
!-----------------------------------------------------------------
! $SOURCE$ $REVISION$
! MASDEV4_7 MODD 2006/05/18 13:07:25
!-----------------------------------------------------------------
!     ######################
MODULE MODD_CLOUDPAR_N
!     ######################
!
!!****  *MODD_CLOUDPAR$N* - DECLARATION OF THE MODEL-N DEPENDANT MICROPHYSICS
!!   CONSTANTS
!!
!!    PURPOSE
!!    -------
!       THE PURPOSE OF THIS DECLARATIVE MODULE IS TO DECLARE  THE
!     MODEL-N DEPENDANT MICROHYSICS CONSTANTS.
!
!!
!!**  IMPLICIT ARGUMENTS
!!    ------------------
!!      NONE
!!
!!    REFERENCE
!!    ---------
!!      BOOK2 OF DOCUMENTATION OF MESO-NH (MODD_CLOUDPARN)
!!
!!    AUTHOR
!!    ------
!!        E. RICHARD   *LABORATOIRE D'AEROLOGIE*
!!
!!    MODIFICATIONS
!!    -------------
!!      ORIGINAL    20/12/95
!!       J.-P. PINTY   29/11/02 ADD C3R5, ICE2, ICE4, ELEC
!!
!-------------------------------------------------------------------------------
!
!*       0.   DECLARATIONS
!             ------------
!
   USE MODD_PARAMETERS, ONLY: JPMODELMAX
   IMPLICIT NONE

   TYPE CLOUDPAR_T
!
      INTEGER :: NSPLITR      !< NUMBER OF REQUIRED SMALL TIME STEP INTEGRATION
                          !! FOR RAIN SEDIMENTATION COMPUTATION
      INTEGER :: NSPLITG      !< NUMBER OF REQUIRED SMALL TIME STEP INTEGRATION
                          !! FOR ICE HYDROMETEOR SEDIMENTATION COMPUTATION
!
!
   END TYPE CLOUDPAR_T

! TYPE(CLOUDPAR_T), DIMENSION(JPMODELMAX), TARGET, SAVE :: CLOUDPAR_MODEL
   TYPE(CLOUDPAR_T), TARGET, SAVE :: CLOUDPARN
   INTEGER, POINTER :: NSPLITR => NULL()
   INTEGER, POINTER :: NSPLITG => NULL()

CONTAINS
   SUBROUTINE CLOUDPAR_ASSOCIATE()
      IMPLICIT NONE
      NSPLITR => CLOUDPARN%NSPLITR
      NSPLITG => CLOUDPARN%NSPLITG
   END SUBROUTINE

END MODULE MODD_CLOUDPAR_N
