MODULE MODE_INI_CLOUDPAR
   IMPLICIT NONE
CONTAINS

   SUBROUTINE INI_CLOUDPAR
      USE MODD_CLOUDPAR_n
      CALL CLOUDPAR_ASSOCIATE()

      ! NSPLITR USED IN RAIN_ICE_OLD FOR SEDIMENTATION
      NSPLITR = 1

      ! NSPLITG USED IN LIMA FOR SEDIMENTATION
      NSPLITG = 1

   END SUBROUTINE
END MODULE
